name: 'Release pipeline'

trigger: none

parameters:
  - name: tag
    displayName: Version Tag
    type: string

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]    


jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: ShellScript@2
        displayName: 'Build & Test'
        inputs:
          scriptPath: './build.sh'

      - task: PublishCodeCoverageResults@1
        displayName: 'Publishing code coverage'
        inputs:
          codeCoverageTool: 'cobertura'
          summaryFileLocation: '$(Build.SourcesDirectory)/**/results.cobertura.xml'
          
      - task: PublishPipelineArtifact@1
        displayName: 'Publishing artifacts'
        inputs:
          artifactName: 'NuGet packages'
          targetPath: 'artifacts/packages'

      - task: NuGetCommand@2
        inputs:
          command: 'push'
          packagesToPush: 'artifacts/packages/*.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'blockmountain nuget'

      - task: GithubRelease@0
        displayName: 'Create GitHub Release'
        condition: eq(variables.isMaster, true)
        inputs:
          gitHubConnection: 'bmresearch_tiago'
          repositoryName: bmresearch/Solnet
          tagSource: manual
          tag: ${{ parameters.tag }}
          assets: 'artifacts/packages/*.nupkg'
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'commitBased'