<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Solana.Extensions</PackageId>
    <Title>Solana.Extensions</Title>
    <PackageProjectUrl>https://github.com/bmresearch/Solnet</PackageProjectUrl>
    <PackageIcon></PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes />
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Solnet.Programs\Solnet.Programs.csproj" />
    <ProjectReference Include="..\Solnet.Rpc\Solnet.Rpc.csproj" />
    <ProjectReference Include="..\Solnet.Wallet\Solnet.Wallet.csproj" />
  </ItemGroup>

  <Import Project="..\..\SharedBuildProperties.props" />
</Project>
