<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Solnet's keypair library for wallet management &amp; transaction signing </Description>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Solana.Wallet</PackageId>
    <Version>10.0.0</Version>
    <Title>Solana.Wallet</Title>
    <PackageTags>solana;solnet;sol;net8;spl</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/bmresearch/Solnet</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://github.com/bmresearch/Solnet</PackageProjectUrl>
    <Copyright>Copyright 2026 © Solnet</Copyright>
    <Product>Solana.Wallet</Product>
    <Company>blockmountain, Bifrost</Company>
    <Authors>blockmountain, Bifrost</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Solnet.Wallet.Test</_Parameter1>
    </AssemblyAttribute>
    <None Include="..\..\assets\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <PackageReference Include="BifrostSecurity" Version="1.0.1" />
  </ItemGroup>

</Project>
